// BrickVault Contract Configuration
// Auto-generated by deployment script - DO NOT EDIT MANUALLY

export const CONTRACT_ADDRESSES = {
  // Infrastructure
  EnvironmentConfig: process.env.NEXT_PUBLIC_ENVIRONMENT_CONFIG_ADDRESS as `0x${string}`,
  MockLayerZeroEndpointA: process.env.NEXT_PUBLIC_MOCK_LAYERZERO_ENDPOINT_A_ADDRESS as `0x${string}`,
  MockLayerZeroEndpointB: process.env.NEXT_PUBLIC_MOCK_LAYERZERO_ENDPOINT_B_ADDRESS as `0x${string}`,
  
  // Tokens
  MockUSDC: process.env.NEXT_PUBLIC_MOCK_USDC_ADDRESS as `0x${string}`,
  ShareOFTAdapter: process.env.NEXT_PUBLIC_SHARE_OFT_ADAPTER_ADDRESS as `0x${string}`,
  OFTUSDC: process.env.NEXT_PUBLIC_OFT_USDC_ADDRESS as `0x${string}`,
  
  // Property Platform
  VaultFactory: process.env.NEXT_PUBLIC_VAULT_FACTORY_ADDRESS as `0x${string}`,
  PropertyDAOFactory: process.env.NEXT_PUBLIC_PROPERTY_DAO_FACTORY_ADDRESS as `0x${string}`,
  PropertyRegistry: process.env.NEXT_PUBLIC_PROPERTY_REGISTRY_ADDRESS as `0x${string}`,
  PropertyVault: process.env.NEXT_PUBLIC_PROPERTY_VAULT_ADDRESS as `0x${string}`,
  PropertyDAO: process.env.NEXT_PUBLIC_PROPERTY_DAO_ADDRESS as `0x${string}`,
} as const;

export const TOKEN_DECIMALS = {
  USDC: 6,
  OFTUSDC: 18,
  VAULT_SHARES: 18,
} as const;

export const NETWORK_CONFIG = {
  name: process.env.NEXT_PUBLIC_NETWORK_NAME || 'localhost',
  chainId: parseInt(process.env.NEXT_PUBLIC_CHAIN_ID || '31337'),
  rpcUrl: process.env.NEXT_PUBLIC_RPC_URL || 'http://localhost:8545',
} as const;

export const LAYERZERO_CONFIG = {
  eidA: parseInt(process.env.NEXT_PUBLIC_LAYERZERO_EID_A || '1'), // Chain A (USDC + Adapter)
  eidB: parseInt(process.env.NEXT_PUBLIC_LAYERZERO_EID_B || '2'), // Chain B (OFTUSDC + Vault)
  endpointA: CONTRACT_ADDRESSES.MockLayerZeroEndpointA,
  endpointB: CONTRACT_ADDRESSES.MockLayerZeroEndpointB,
} as const;

export const PROPERTY_CONFIG = {
  fundingTarget: process.env.NEXT_PUBLIC_FUNDING_TARGET || '0',
  vaultDepositCap: process.env.NEXT_PUBLIC_VAULT_DEPOSIT_CAP || '0',
} as const;
